### ISSUE TITLE
Query about concurrent access of bridge

### ISSUE THREAD

**Issue by programmer215-bob** [meekalpha/nordvik-threads-c#1]
How to achieve that one truck and one car can go on bridge same time?? @meekalpha

**Comment by meekalpha** [comment]
Can you give a bit more detail? Are you saying that the bridge can hold a car then a truck, or a truck then a car, in either direction? But it can't hold e.g. two cars?

**Comment by programmer215-bob** [comment]
I want to say it can hold either 3 cars on same direction or a car and truck on same direction. I means if a car is already on bridge then we can send 2 more cars or one truck on bridge
________________________________

**Comment by programmer215-bob** [comment]
@meekalpha ???

**Comment by meekalpha** [comment]
I don't know off the top of my head, I wrote this code 8 years ago for university. It sounds like you are doing a similar assignment. I hope my example is helpful for you, and good luck writing your code.

**Comment by programmer215-bob** [comment]
@meekalpha  yeah it helped me a lot btw thanks
